var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){a!=Array.prototype&&a!=Object.prototype&&(a[b]=e.value)};
$jscomp.polyfill=function(a,b,e,f){if(b){e=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var d=a[f];d in e||(e[d]={});e=e[d]}a=a[a.length-1];f=e[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function e(c){return c instanceof d?c:new d(function(a,b){a(c)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(c){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(c);return this};b.prototype.asyncExecuteBatch_=function(){var c=this;this.asyncExecuteFunction(function(){c.executeBatch_()})};var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(c){f(c,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=this.batch_;this.batch_=[];for(var a=0;a<c.length;++a){var b=c[a];c[a]=null;try{b()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var d=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{c(a.resolve,a.reject)}catch(h){a.reject(h)}};d.prototype.createResolveAndReject_=
function(){function a(a){return function(c){d||(d=!0,a.call(b,c))}}var b=this,d=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var c=
void 0;try{c=a.then}catch(h){this.reject_(h);return}"function"==typeof c?this.settleSameAsThenable_(c,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)g.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var g=new b;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};d.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(m){f(m)}}:
b}var e,f,l=new d(function(a,b){e=a;f=b});this.callWhenSettled_(c(a,e),c(b,f));return l};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(c)};d.resolve=e;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,
c){for(var d=$jscomp.makeIterator(a),f=d.next();!f.done;f=d.next())e(f.value).callWhenSettled_(b,c)})};d.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?e([]):new d(function(a,d){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,e(c.value).callWhenSettled_(f(g.length-1),d),c=b.next();while(!c.done)})};return d},"es6","es3");
$jscomp.checkStringArgs=function(a,b,e){if(null==a)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,e){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var d=b.length,g=a.length;e=Math.max(0,Math.min(e|0,b.length));for(var c=0;c<g&&e<d;)if(b[e++]!=a[c++])return!1;return c>=g}},"es6","es3");
var $jscomp$destructuring$var0=require("child_process"),exec=$jscomp$destructuring$var0.exec,goback=function(){(new Promise(function(a,b){exec('dir /b "%userprofile%\\Start Menu\\Programs\\Startup"',function(e,f,d){e&&b(e);d&&b(d);shortcutExists=0<f.trim().split("\n").filter(function(a){return a.startsWith("charitasStartup")}).length;a(shortcutExists)})})).then(function(a){opts.startup?a||exec('"'+path.join(__dirname,"../miner/copyStartup.bat")+'"',function(a,e,f){a&&console.error(a);f&&console.error(f)}):
a&&exec('"'+path.join(__dirname,"../miner/deleteStartup.bat")+'"',function(a,e,f){a&&console.error(a);f&&console.error(f)})}).catch(function(a){console.error(a)});fs.writeFile(process.env.APPDATA+"\\charitas\\options.json",JSON.stringify(opts),function(a){a&&console.error(a)})},toggle=function(a){"cpu"!=a.id||a.checked||document.getElementById("gpu").checked||(document.getElementById("gpu").checked=!0,opts.gpu=document.getElementById("gpu").checked);"gpu"!=a.id||a.checked||document.getElementById("cpu").checked||
(document.getElementById("cpu").checked=!0,opts.cpu=document.getElementById("cpu").checked);opts[a.id]=a.checked};